name=input("enter your name: ")
roll=int(input("enter your roll no: "))
age=int(input("enter your age: "))
class1=int(input("enter your class: "))
school=input("enter your school name: ")
print("your name is",name)
print("your roll no",roll)
print("your age is",age)
print("your class is",class1)
print("your school name is",school)