a=int(input("enter the first number"))
b=int(input("enter the second number"))
print("the value of a","=",a)
print("the value of b","=",b)
c=b
b=a
a=c
print("value of a is","=",a)
print("the value of b is","=",b)